node:
    node_uid: nd_vydisdlb7k
    name: resolver-local-15
    version: 1.0.0
    region: us-east-1
    country: US
    provider: local
    public_ipv4: 127.0.0.1
listen:
    doh: 8445
    udp: 5356
control_plane:
    endpoint: http://localhost:8081
    api_key: ocnd_DgBW1NmRgVdMLKaVofYmN1gkpvvHZFLTsO9GStTg
    secret: hmk_nghi2usuotyntsgu955vcgkbu6s4dmbi
    node_id: 15
    heartbeat_interval: 30
    config_poll_interval: 5
    profiles_path: ./configs
upstream:
    - 1.1.1.1
    - 8.8.8.8
logging:
    level: debug
    buffer_path: /tmp/dns-logs-node2
nats:
    enabled: false
redis:
    enabled: false
geodns:
    enabled: true
    endpoint: http://127.0.0.1:5354
    request_timeout_seconds: 3
