server:
    listen_addr: :15354
    listen_dns_addr: :10053
    console_health_url: https://test-dns.ocerlinkdata.com/api/v1/internal/geodns/health-view
    console_health_token: yqocGak1lHgEdeIUeB2qHtxUoQAJlG5F8j0wUbES
    refresh_interval: 15s
    request_timeout_seconds: 5
routing:
    global_fallback_region: global
node:
    token: yqocGak1lHgEdeIUeB2qHtxUoQAJlG5F8j0wUbES
    node_id: phqval3wur
    api_endpoint: https://test-dns.ocerlinkdata.com
    api_key_path: /www/wwwroot/test-dns.ocerlinkdata.com/demo-dns/geodns/configs/api_key
